"""
Pydantic v2 schemas and data transfer models for the LegalRAG FastAPI API.
"""

from typing import List, Optional, Literal, Any
from pydantic import BaseModel, Field, field_validator


class QueryRequest(BaseModel):
    """
    Incoming search and question-answering request schema.
    """

    question: str = Field(
        ...,
        description="Legal inquiry or question regarding Indian High Court judgments.",
        examples=["What are the conditions for granting anticipatory bail under Section 438 CrPC?"],
    )

    @field_validator("question", mode="before")
    @classmethod
    def validate_question(cls, value: Any) -> str:
        """Validates that question is a non-empty string and strips whitespace."""
        if not isinstance(value, str):
            raise ValueError("Question must be a string.")
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("Question must not be empty or whitespace-only.")
        return cleaned


class Citation(BaseModel):
    """
    Metadata for a context passage cited in the generated answer.
    """

    chunk_id: str = Field(..., description="Unique chunk identifier (e.g. CNR_chunk_0).")
    cnr: Optional[str] = Field(default=None, description="Case Record Number / unique case identifier.")
    court_code: Optional[str] = Field(default=None, description="Court code identifying the High Court.")
    decision_date: Optional[str] = Field(default=None, description="Decision date of the judgment.")
    title: Optional[str] = Field(default=None, description="Case title or parties involved.")


class QueryResponse(BaseModel):
    """
    Structured outcome of the grounded legal question-answering pipeline.
    """

    answer: str = Field(
        ...,
        description="Grounded answer text generated by the pipeline, or error details if failed.",
    )
    citations: List[Citation] = Field(
        default_factory=list,
        description="List of cited source passages with case metadata.",
    )
    retrieved_chunk_ids: List[str] = Field(
        default_factory=list,
        description="Ordered list of chunk IDs retrieved across the multi-stage cascade.",
    )
    retrieve_ms: float = Field(
        ...,
        description="Hybrid retrieval stage execution latency in milliseconds.",
    )
    rerank_ms: float = Field(
        ...,
        description="Cross-encoder reranking stage execution latency in milliseconds.",
    )
    generate_ms: float = Field(
        ...,
        description="LLM answer generation stage execution latency in milliseconds.",
    )
    total_ms: float = Field(
        ...,
        description="End-to-end request latency in milliseconds.",
    )
    status: Literal["ok", "generation_error", "retrieval_error"] = Field(
        ...,
        description="Pipeline execution status indicating success or specific subsystem failure.",
    )


class HealthResponse(BaseModel):
    """
    Health check response model.
    """

    status: Literal["ok", "degraded"] = Field(
        ...,
        description="Overall service operational status.",
    )
    environment: str = Field(
        ...,
        description="Active runtime environment mode ('local_stub' or 'production').",
    )
